name: Verify 
description: Verify signature and SBOM Attestation

inputs:
  image: 
    description: URL to the Image 
    required: true 

runs:
  using: composite

  steps:      
    - name: Verify Keyless Signature (Cosign)
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
      run: |
        set -eu
        cosign verify "${IMAGE}" \
        --certificate-identity-regexp 'https://github.com/ej-east/redoubt/\.github/workflows/ci\.yaml@.*' \
        --certificate-oidc-issuer https://token.actions.githubusercontent.com
    - name: Verify SBOM Attestation (Cosign)
      env:
        IMAGE: ${{ inputs.image }}
      run: |
        set -eu
        cosign verify-attestation \
          --type spdxjson \
          --certificate-identity-regexp 'https://github.com/ej-east/redoubt/\.github/workflows/ci\.yaml@.*' \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \
          "${IMAGE}" > /dev/null